name: 'Search'
description: 'Configures search for Consumer Mesh'
type: 'Content type'

recipes:

install:
  - search_api
  - search_api_db

config:
  import:
    search_api: '*'
    search_api_db: '*'
  actions:
